release: v2.42.0 (#2177)
* version

Signed-off-by: svetoslav-nikol0v <svetoslav.nikolov@limechain.tech>

* release notes

Signed-off-by: svetoslav-nikol0v <svetoslav.nikolov@limechain.tech>

* stringify the value

Signed-off-by: svetoslav-nikol0v <svetoslav.nikolov@limechain.tech>

* address books update

Signed-off-by: svetoslav-nikol0v <svetoslav.nikolov@limechain.tech>

* chore: update version, changelog, address books

Signed-off-by: svetoslav-nikol0v <svetoslav.nikolov@limechain.tech>

* feature: handling and externalisation improvements for account nonce updates (#2176)

* chore: all necessary stuff for release

Signed-off-by: svetoslav-nikol0v <svetoslav.nikolov@limechain.tech>

* feature: add signerNonce field

Signed-off-by: svetoslav-nikol0v <svetoslav.nikolov@limechain.tech>

---------

Signed-off-by: svetoslav-nikol0v <svetoslav.nikolov@limechain.tech>

* chore: remove .only

Signed-off-by: svetoslav-nikol0v <svetoslav.nikolov@limechain.tech>

* fix: release workflow

Signed-off-by: svetoslav-nikol0v <svetoslav.nikolov@limechain.tech>

* chore: skip the test suit for ethereum transaction

Signed-off-by: svetoslav-nikol0v <svetoslav.nikolov@limechain.tech>

* chore: add more details

Signed-off-by: svetoslav-nikol0v <svetoslav.nikolov@limechain.tech>

* chore: typo

Signed-off-by: svetoslav-nikol0v <svetoslav.nikolov@limechain.tech>

---------

Signed-off-by: svetoslav-nikol0v <svetoslav.nikolov@limechain.tech>

diff --git a/.github/workflows/publish_release.yaml b/.github/workflows/publish_release.yaml
--- a/.github/workflows/publish_release.yaml
+++ b/.github/workflows/publish_release.yaml
@@ -73,7 +73,7 @@ jobs:
           RELEASE_VERSION="$(semver get release "${REF_NAME}")"
           PREREL_VERSION="$(semver get prerel "${REF_NAME}")"
           PREREL_VERSION_LC="$(printf "%s" "${PREREL_VERSION}" | tr '[:upper:]' '[:lower:]')"
-          
+
           IS_PRERELEASE="false"
           [[ -n "${PREREL_VERSION}" ]] && IS_PRERELEASE="true"
           
@@ -106,6 +106,11 @@ jobs:
             exit 1
           fi
           
+          if [[ "${{ steps.tag.outputs.type }}" != "production" && "${{ steps.tag.outputs.type }}" != "beta" ]]; then
+            echo "::error title=Unsupported PreRelease::The tag '${{ steps.tag.outputs.name }}' is an unsupported prerelease tag. Only 'beta' prereleases are supported."
+            exit 2
+          fi
+
           if [[ "${{ steps.tag.outputs.type }}" != "production" && "${{ steps.tag.outputs.type }}" != "beta" ]]; then
             echo "::error title=Unsupported PreRelease::The tag '${{ steps.tag.outputs.name }}' is an unsupported prerelease tag. Only 'beta' prereleases are supported."
             exit 2
